// Bundles the typed Workstation SDK (packages/sdk) into a single self-contained ESM string,
// emitted as `modules/sandbox/sdkBundle.ts`. That string is injected into the sandbox VM as
// `node_modules/workstation/index.mjs`, so agent-written code can `import { createClient } from
// "workstation"` and call every contract operation. Re-run whenever the contract/SDK changes:
//
//   bun run scripts/bundle-sdk.ts
//
// (wired as the `build:sdk-bundle` package script).

const result = await Bun.build({
  entrypoints: ["packages/sdk/src/index.ts"],
  target: "node",
  format: "esm",
  minify: false,
});

if (!result.success) {
  console.error("[bundle-sdk] build failed");
  for (const log of result.logs) console.error(log);
  process.exit(1);
}

const code = await result.outputs[0]!.text();
const out =
  "// AUTO-GENERATED by scripts/bundle-sdk.ts — do not edit by hand.\n" +
  "// Single-file ESM bundle of the `workstation` SDK, injected into the sandbox VM.\n" +
  `export const SDK_BUNDLE: string = ${JSON.stringify(code)};\n`;

await Bun.write("modules/sandbox/sdkBundle.ts", out);
console.log(`[bundle-sdk] wrote modules/sandbox/sdkBundle.ts (${code.length} bytes of SDK)`);
